app/authorization/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField,\
 SelectField, IntegerField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User, Permission


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log In')


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])
    username = StringField('Username', validators=[
        DataRequired(), Length(1, 64),
        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
               'Usernames must have only letters, numbers, dots or '
               'underscores')])
    password = PasswordField('Password', validators=[
        DataRequired(), EqualTo('password2', message='Passwords must match.')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data.lower()).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if User.query.filter_by(name=field.data).first():
            raise ValidationError('Username already in use.')

class ManagementForm(FlaskForm):
    function= SelectField('Action', 
        choices=[('Pending',''),('Update', 'Update'),('Delete', 'Delete') ]
    )
    
    id_=IntegerField('ID',validators=[DataRequired()])
    
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])
    username = StringField('Username', validators=[
        DataRequired(), Length(1, 64),
        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
               'Usernames must have only letters, numbers, dots or '
               'underscores')])
    role = SelectField('Role', 
        choices=[(entry[0],entry[0]) for entry in Permission]
    )
    submit = SubmitField('Send')
    

app/authorization/__init__.py
from flask import Blueprint

authorization = Blueprint('authorization', __name__)

from . import views

app/authorization/views.py
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user, login_required
from . import authorization
from .. import db
from ..models import User, Permission
from .forms import LoginForm, RegistrationForm, ManagementForm




@authorization.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            next_ = request.args.get('next')
            if next_ is None or not next_.startswith('/'):
                next_ = url_for('main.index')
            return redirect(next_)
        flash('Invalid email or password.')
    return render_template('authorization/login.html', form=form)


@authorization.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.index'))


@authorization.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data.lower(),
                    name=form.username.data,
                    password=form.password.data,
                    role_id=2)
        db.session.add(user)
        db.session.commit()

        flash('A confirmation email has been sent to you by email.')
        return redirect(url_for('authorization.login'))
    return render_template('authorization/register.html', form=form)

@authorization.route('/management', methods=['GET', 'POST'])
def manage():
    form = ManagementForm()
    users = User.query.all()
    
    if form.validate_on_submit():
        if form.function.data=='Pending':
            return redirect(url_for('authorization.manage'))
        
        user=User.query.filter_by(id=form.id_.data).first()
        if form.function.data=='Update':
            user.name=form.username.data
            user.email=form.email.data.lower()
            user.role_id=[entry[1] for entry in Permission 
                          if entry[0]==form.role.data][0]
            
            db.session.add(user)
        elif form.function.data=='Delete':
            db.session.delete(user)
        
        db.session.commit()
            
        return redirect(url_for('authorization.manage'))
        
    return render_template('authorization/Management.html', form=form,users=users)

app/templates/authorization/Management.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flask - Management{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Management</h1>
</div>
<div class="col-sm-2">
    {{ wtf.quick_form(form) }}
</div>
<div class="col-md-4">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Email</th>
      <th scope="col">Username</th>
      <th scope="col">Role</th>
    </tr>
  </thead>
  <tbody>
  {% for user in users %}
    <tr>
      <th scope="row">{{user.id}}</th>
      <td>{{user.email}}</td>
      <td>{{user.name}}</td>
      <td>{{user.role}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

app/templates/authorization/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Login{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Login</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
    <br>
    <p>New user? <a href="{{ url_for('authorization.register') }}">Click here to register</a>.</p>
</div>
{% endblock %}

app/templates/authorization/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Register{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}